services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - DATA_SOURCE_URL=${DATA_SOURCE_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - SUPABASE_ACCESS_KEY=${SUPABASE_ACCESS_KEY}
      - SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY}
