services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - DATA_SOURCE_URL=${DATA_SOURCE_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - SUPABASE_ACCESS_KEY=${SUPABASE_ACCESS_KEY}
      - SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY}

    depends_on:
       db:
         condition: service_healthy
  db:
     image: postgres
     restart: always
     user: postgres

     secrets:
       - db-password
     volumes:
       - db-data:/var/lib/postgresql/data
     environment:
       - POSTGRES_DB=example
       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
     expose:
       - 5432
     healthcheck:
       test: [ "CMD", "pg_isready" ]
       interval: 10s
       timeout: 5s
       retries: 5
volumes:
   db-data:
secrets:
   db-password:
     file: db/password.txt